import type { Fixture, Player } from './domain';
// Illustrative fixtures and stats, never a current football feed.
export const demoFixtures: Fixture[] = [
  {
    id: 'demo-1',
    opponent: 'Athletic Club',
    code: 'ATH',
    home: true,
    competition: 'La Liga',
    kickoff: '2026-09-12T19:00:00Z',
    stadium: 'Spotify Camp Nou',
    status: 'scheduled',
  },
  {
    id: 'demo-2',
    opponent: 'Inter',
    code: 'INT',
    home: false,
    competition: 'Champions League',
    kickoff: '2026-09-16T19:00:00Z',
    stadium: 'San Siro',
    status: 'scheduled',
  },
  {
    id: 'demo-3',
    opponent: 'Villarreal',
    code: 'VIL',
    home: false,
    competition: 'La Liga',
    kickoff: '2026-09-20T16:30:00Z',
    stadium: 'Estadio de la Cerámica',
    status: 'scheduled',
  },
  {
    id: 'demo-4',
    opponent: 'Real Sociedad',
    code: 'RSO',
    home: true,
    competition: 'La Liga',
    kickoff: null,
    stadium: 'Spotify Camp Nou',
    status: 'scheduled',
  },
  {
    id: 'demo-5',
    opponent: 'Valencia',
    code: 'VAL',
    home: true,
    competition: 'La Liga',
    kickoff: '2026-09-05T19:00:00Z',
    stadium: 'Spotify Camp Nou',
    status: 'finished',
    score: [3, 1],
  },
];
export const demoPlayers: Player[] = [
  {
    id: 'lamine-yamal',
    name: 'Lamine Yamal',
    number: 10,
    position: 'Forward',
    nationality: 'Spain',
    availability: 'Unknown',
    appearances: 4,
    goals: 2,
    assists: 3,
    minutes: 338,
  },
  {
    id: 'pedri',
    name: 'Pedri',
    number: 8,
    position: 'Midfielder',
    nationality: 'Spain',
    availability: 'Unknown',
    appearances: 4,
    goals: 1,
    assists: 2,
    minutes: 351,
  },
  {
    id: 'raphinha',
    name: 'Raphinha',
    number: 11,
    position: 'Forward',
    nationality: 'Brazil',
    availability: 'Unknown',
    appearances: 4,
    goals: 3,
    assists: 1,
    minutes: 325,
  },
  {
    id: 'pau-cubarsi',
    name: 'Pau Cubarsí',
    number: 5,
    position: 'Defender',
    nationality: 'Spain',
    availability: 'Unknown',
    appearances: 4,
    goals: 0,
    assists: 0,
    minutes: 360,
  },
  {
    id: 'gavi',
    name: 'Gavi',
    number: 6,
    position: 'Midfielder',
    nationality: 'Spain',
    availability: 'Unknown',
    appearances: 3,
    goals: 0,
    assists: 1,
    minutes: 189,
  },
  {
    id: 'joan-garcia',
    name: 'Joan Garcia',
    number: 13,
    position: 'Goalkeeper',
    nationality: 'Spain',
    availability: 'Unknown',
    appearances: 4,
    goals: 0,
    assists: 0,
    minutes: 360,
  },
];
export const officialLinks = [
  {
    title: 'First-team news',
    category: 'CLUB UPDATES',
    description:
      'Confirmed announcements, training reports and medical updates from the club.',
    url: 'https://www.fcbarcelona.com/en/football/first-team/news',
  },
  {
    title: 'Official match schedule',
    category: 'FIXTURES',
    description:
      'Check the club’s published fixtures and confirmed kickoff times.',
    url: 'https://www.fcbarcelona.com/en/futbol/primer-equipo/calendario',
  },
];
